FROM node:20-alpine

WORKDIR /app

ENV YARN_NODE_LINKER=node-modules
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package.json yarn.lock ./

# Yarn 설정을 먼저 하고 정상적으로 설치
RUN yarn set version stable && \
    yarn config set enableImmutableInstalls false && \
    yarn config set nodeLinker node-modules && \
    yarn install

COPY . .

EXPOSE 5173

CMD ["yarn", "dev", "--host", "0.0.0.0"]
